// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmlztmobxmvuyjwqwvgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbHp0bW9ieG12dXlqd3F3dmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTU2NjAsImV4cCI6MjA2NTY3MTY2MH0.PLu8yRr0WEI2D44P2exeWtzXXZ_4-0EKAvq3DIrH50A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);